# 相关配置说明
  # favicon: 网站图标
  # avatar: 主题用户头像与昵称
  # rss: rss订阅
  # gtag: CNZZ统计
  # comments: 文章评论系统
  # navbar: 主题页面导航栏
  # catalog: 文章目录
  # prevnext: 文章末尾的上一页与下一页
  # friends: 友链
  # footer: 页脚信息
  # search: 文章搜索
  # colorSwitch: 深/浅配色切换
  # postShare: 文章分享

# enable: 是否开启相应功能，可选true || false

# 网站图标
favicon:
  enable: true
  icon: /static/images/favicon.ico
  touch_icon: /static/images/favicon.ico

# 用户头像与昵称
avatar:
  author_photo: /static/images/avatar.jpeg
  author_nickname: 杨林的博客
  path: /

# CNZZ统计
cnzz:
  enable: true
  url: https://s9.cnzz.com/z_stat.php?id=1280512941&online=1&show=line

# 文章评论系统
comments:
  enable: true
  # 目前仅支持valine评论
  valine:
    # https://valine.js.org/quickstart.html#%E8%8E%B7%E5%8F%96APP-ID-%E5%92%8C-APP-Key
    # 进入以上网址查看官方教程
    enable: true
    appId: gxUGOlvmRdJDF7uhm9hQS44B-gzGzoHsz
    appKey: 369PuooqB9swyor4RiJttTxz
    placeholder: Welcome!
    avatar: retro
    vempty_display: true

# 主题页面导航栏
navbar:
  -
    name: 主页
    enable: true
    path: /
    key: home
  -
    name: 归档
    enable: true
    path: /archives/
    key: archives
  -
    name: 分类
    enable: false
    path: /categories/
    key: categories
  -
    name: 标签
    enable: true
    path: /tags/
    key: tags
  -
    name: 朋友
    enable: true
    path: /friends/
    key: friends
  -
    name: 关于
    enable: true
    path: /about/
    key: about

# 文章目录
catalog:
  enable: true

# 文章末尾的上一页与下一页
prevnext:
  enable: true

# 友链详细信息：支持多个友链
friends:
  # nickname: 昵称
  # site: 地址
  # meta: 描述
  -
    nickname: Zcheng
    site: https://zcheng.site/
    meta:
  -
    nickname: Hexo
    site: https://hexo.io/
    meta:

# 页脚信息
footer:
  # social: 社交方式
  # more: 更多页脚信息
  social:
    # name: 名称
    # icon: 图标，目前仅支持IconFont部分图标
    # path: 地址
    -
      name: github
      icon: github
      path: https://github.com/index-js
    -
      name: email
      icon: envelope
      path: mailto:i@yangl.in
    -
      # rss需安装 hexo-generator-feed 插件
      # 具体参照https://github.com/hexojs/hexo-generator-feed
      name: rss
      icon: rss
      path: /atom.xml

  more:
    -
      name: Theme by Oranges | Powered by Hexo
      path: https://github.com/zchengsite/hexo-theme-oranges
    - 
      name: 蜀ICP备2021019109号-1
      path: https://beian.miit.gov.cn/

# 文章搜索
search:
  enable: true
  placeholder: 

# 深/浅配色切换
colorSwitch:
  enable: true

# 文章分享
postShare:
  enable: true

  twitter:
    enable: true

  facebook:
    enable: true
